# Generated by Django 3.0.2 on 2020-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnidetailmodel',
            old_name='status',
            new_name='Verified',
        ),
        migrations.AddField(
            model_name='alumnidetailmodel',
            name='College',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD'), ('FOURTH', 'FOURTH'), ('FIFTH', 'FIFTH'), ('SIXTH', 'SIXTH'), ('SEVENTH', 'SEVENTH'), ('EIGHTH', 'EIGHTH')], default='None', max_length=80),
        ),
        migrations.AlterField(
            model_name='alumnidetailmodel',
            name='About',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumnidetailmodel',
            name='Work',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumnidetailmodel',
            name='Year_Joined',
            field=models.CharField(max_length=4),
        ),
    ]
