# Generated by Django 3.0.2 on 2020-01-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200107_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidetailmodel',
            name='Verified',
            field=models.BooleanField(),
        ),
    ]
