# Generated by Django 3.0.2 on 2020-01-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200108_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidetailmodel',
            name='Branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumnidetailmodel',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
