# Generated by Django 3.0.2 on 2020-01-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200108_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidetailmodel',
            name='Email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='alumnidetailmodel',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
